### PR TITLE
Update secrets provider program to use KMS secret

### PR DESCRIPTION
**Pull request by komalali**
This program was not correctly specifying the secrets provider as part of the stack settings required to maintain usage on `select`. Changed this to use KMS instead of passphrase to make the failure/usage more obvious.

Also added a separate passphrase usage example after PR feedback.

Various fixes to make tests pass since this hasn't been updated in a while.

Fixes: https://github.com/pulumi/pulumi/issues/8183

### CODE REVIEW

**Comment by komalali** [comment]
@EvanBoyle it's unrelated to this PR but do you have any ideas what might be going on in https://github.com/pulumi/automation-api-examples/pull/34/checks?check_run_id=3863913463

**Comment by EvanBoyle** [comment]
Looks like the example is borked:

Screen Shot 2021-10-11 at 2 38 48 PM

**Comment by EvanBoyle** [comment]
> Changed this to use KMS instead of passphrase to make the failure/usage more obvious.
@komalali I remember @leezen adding this example. The purpose if I recall correctly was to have an example for each of:

1. Pulumi managed secrets
2. Azure/KMS secrets (other examples)
3. Passphrase secrets (this example)

Would be great if our fix actually kept the passphrase provider to appropriately document usage here

**Comment by komalali** [comment]
Fix for the test failure is here: https://github.com/pulumi/examples/pull/1100 but it is unrelated to the changes in this PR.

**Pull request merged**
