### PR TITLE
Python examples

### PR DESCRIPTION
**Pull request by komalali**
**Examples**

- [x] Inline program
- [x] Cross-language program
- [x] Local program
- [x] Database migration
- [x] Pulumi over HTTP

### CODE REVIEW

**Review by EvanBoyle — COMMENTED** [review]
Looks good so far! Do you know what the plan is for blogging about this? 

It would be awesome to write a python specific blog to announce this, with perhaps some domain specific examples. Data science training and workflows are one that come to mind. Perhaps something with the jupyter example that you demoed? Maybe a program that set's up spark or sagemaker and then makes requests to them to make predictions? 

In addition to any new blogs/content we produce, it's probably a good idea to update the launch blog and add python example content (https://www.pulumi.com/blog/automation-api/) given all the links that are pointing to it already, SEO, etc.

**Comment by komalali** [comment]
@EvanBoyle Yeah I think a python blog with data science workflows makes a lot of sense. DB migration example is also a common python workflow. I'll spend some time on this in the upcoming week.

**Comment by komalali** [comment]
@EvanBoyle I think maybe we can merge this branch and I'll work on my notebook example in a separate PR.

**Comment by clstokes** [comment]
> @EvanBoyle I think maybe we can merge this branch and I'll work on my notebook example in a separate PR.

Merging what's available now would be great so we can start sharing these with customers that have expressed interest. :shipit:

**Review by EvanBoyle — COMMENTED** [review]
🎉

**Pull request merged**
